### ISSUE TITLE
Remote disconnects after 30min

### ISSUE THREAD

**Issue by visiover** [evelyn9191/stock_predictions_scraper#8]
Hey Evelyn,

Thanks a lot for sharing this awesome repository.

I'm having trouble running the application the remote disconnects after exactly 30min.

`requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

**Comment by evelyn9191** [comment]
Hello visiover,

happy to hear you like the repo!

Did you change the sleep time intervals between the scraping? 
Is this issue happening during the `walletinvestor` scraping or the `Nasdaq` scraping?

This error seems to be often connected with excessive number of calls sent within a short time or due to a similar race condition of the remote server. Not sure if I can help more with this issue, but details may shed some light on it.
